apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: e2e-tests-go-byyhzdzx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-go-byyhzdzx 
  name: e2e-tests-go-byyhzdzx
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: e2e-tests-go-byyhzdzx 
